version: "3.9"

services:
  db:
    container_name: finansialplanned_postgres
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./database-data/:/var/lib/postgresql/data/
    networks:
      - finansialplanned_db
networks:
  finansialplanned_db:
